title: "Liam's Blog"
url: "http://liamchzh.github.io"
author: "Liam"
email: "liamchzh@gmail.com"
description: "Liam's Blog"

auto: false
source: .
paginate: 10
paginate_files:
 - index.html


markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-48154886-1'
  getclicky :
    site_id :
